# Generated by Django 5.2.4 on 2025-08-01 09:19

import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('invitation_link', models.URLField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_events', to='organization.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('campaign_type', models.CharField(choices=[('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp')], default='WHATSAPP', max_length=30)),
                ('guests_category', models.CharField(choices=[('SOLO_GUESTS', 'Solo Guests (Standard General)'), ('COUPLES_INVITED', '+1/Couples Invited'), ('MEAL_OR_PREFERENCE_REQUIRED', 'Meal/Preference required'), ('GROUPS', 'Groups'), ('VIP_OR_PRIORITY_GUESTS', 'VIP/Priority Guests'), ('KIDS_INCLUDED_OR_FAMILY', 'Kids Included/Family')], max_length=30)),
                ('is_meal_choice', models.BooleanField(default=False, help_text='Dietary preferences or menu selection')),
                ('is_dietary_restrictions', models.BooleanField(default=False, help_text='Allergies and dietary requirements')),
                ('is_parking_needed', models.BooleanField(default=False, help_text='Whether guest needs parking')),
                ('is_accessibility_needed', models.BooleanField(default=False, help_text='Any accessibility accommodations')),
                ('is_accommodation_required', models.BooleanField(default=False, help_text='Hotel or lodging needs')),
                ('description', models.TextField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_campaigns', to='organization.organization')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_campaigns', to='event.event')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_guests', to='event.campaign')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
