# Generated by Django 5.2.4 on 2025-07-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='dialog_api_key',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
