# Generated by Django 5.2.4 on 2025-07-29 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_organization_dialog_api_key'),
        ('subscription', '0002_alter_subscriptionplan_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organizations_subscription_plan', to='organization.organization'),
        ),
    ]
